=== kadim-git/LangPosseisson/_pilotSchema_9.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
	<xs:element name="LanguageData">
		<xs:complexType>
			<xs:sequence>
				<xs:element maxOccurs="unbounded" ref="Language"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="Language">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="GeneralInfo"/>
				<xs:element ref="Possession"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="GeneralInfo">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="LangID" type="xs:token" />
				<xs:element name="ISO639-3" type="xs:string"/>
				<xs:element name="Location" type="xs:string"/>
				<xs:element name="Country" maxOccurs="unbounded" type="xs:string"/>
				<xs:element name="GeneticRelation" type="xs:string"/>
				<xs:element name="WordOrder" type="xs:string"/>
				<xs:element name="CaseSystem" type="xs:string"/>
				<xs:element name="NominalPhrase" type="xs:string"/>
				<xs:element name="InterchangeaStrategies" type="xs:string"/>
				<xs:element name="RelStrategies" type="xs:string"/>
			
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="Possession">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="PronominalPossession"/>
				<xs:element ref="NominalPossession"/>
			</xs:sequence>
		</xs:complexType>
		
		<xs:key name="keyStrategy">
			<xs:selector xpath="./PronominalPossession/StrategyPronom" />
			<xs:field xpath="@StrategyID" />
		</xs:key>
		
		<xs:keyref name="keyrefStrategy" refer="keyStrategy">
			<xs:selector xpath="./NominalPossession/Strategy/PronStrategy" />
			<xs:field xpath="@refStrategyID" />
		</xs:keyref>
	
	</xs:element>
	
	<xs:element name="PronominalPossession">
		<xs:complexType>
			<xs:sequence>
				<!--<xs:element maxOccurs="unbounded" ref="Strategy"/>-->
				<xs:element maxOccurs="unbounded" ref="StrategyPronom"/>
				<xs:element minOccurs="0" maxOccurs="unbounded" ref="StrategyPronomNonCanonical"/>
				</xs:sequence>
		</xs:complexType>
	</xs:element>
	
	<xs:element name="NominalPossession">
		<xs:complexType>
			<xs:sequence>
				<xs:choice minOccurs="0" maxOccurs="unbounded">
					<xs:element ref="StrategyNomMorph"></xs:element>
					<xs:element ref="StrategyNomJuxt"></xs:element>
					<xs:element ref="StrategyNomPron"></xs:element>
					<xs:element ref="StrategyNomNonCanonical"></xs:element>
					
					
					<!-- TEMP ELEMENT TO DELETE WHEN STRATEGIES ARE CORRECTED-->
					<xs:element ref="Strategy"/>
				
				</xs:choice>
			
			</xs:sequence>
		
		</xs:complexType>
	</xs:element>


	
	<xs:element name="StrategyNomMorph">
		<xs:complexType>
			<xs:sequence>
				
				<xs:element ref="Semantics"/>
				<xs:element ref="Morphology"/>
				<xs:element ref="SyntEnvironment"/>
			
			</xs:sequence>
			<xs:attribute name="Complexity" use="required" type="ComplexityAttrType"/>
			<xs:attribute name="StrategyID" use="required" type="xs:string"/>
		
		</xs:complexType>
	</xs:element>

	<xs:element name="StrategyNomJuxt">
		<xs:complexType>
			<xs:sequence>
			
				<xs:element ref="Semantics"/>
				<xs:element ref="Juxtaposition"/>
				<xs:element ref="SyntEnvironment"/>
			
			</xs:sequence>
			<xs:attribute name="StrategyID" use="required" type="xs:string"/>
		
		</xs:complexType>
	</xs:element>
	
		<xs:element name="StrategyNomPron">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="PronStrategy" minOccurs="1" maxOccurs="unbounded">
					<xs:complexType>
						<xs:attribute name="refStrategyID" use="required" type="xs:string"></xs:attribute>
					</xs:complexType>
				</xs:element>
				
				<xs:element minOccurs="0" ref="Semantics"/>
				<xs:choice>
					
					<xs:element minOccurs="0" ref="Juxtaposition"/>
					<xs:element minOccurs="0" ref="Morphology"/>
				</xs:choice>
				
				<xs:element ref="SyntEnvironment"/>
			
			</xs:sequence>
			<xs:attribute name="StrategyID" use="required" type="xs:string"/>
		
		</xs:complexType>
	</xs:element>

	
	
	<xs:element name="StrategyNomNonCanonical">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Morphology"/>
				<xs:element ref="SyntEnvironment"/>
			
			</xs:sequence>
			<xs:attribute name="Complexity" type="ComplexityAttrType" use="required" />
			<xs:attribute name="StrategyID" type="xs:string" use="required" />
		
		</xs:complexType>
	</xs:element>
	
	
	<xs:element name="StrategyPronom">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Semantics"/>
				<xs:element ref="Morphology"/>
				<xs:element ref="SyntEnvironment"/>
			
			</xs:sequence>
			<xs:attribute name="Complexity" type="ComplexityAttrType" use="required" />
			<xs:attribute name="StrategyID" type="xs:string" use="required" />
		
		</xs:complexType>
	</xs:element>
	
	<xs:element name="StrategyPronomNonCanonical">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Morphology"/>
				<xs:element ref="SyntEnvironment"/>
			
			</xs:sequence>
			<xs:attribute name="Complexity" type="ComplexityAttrType" use="required" />
			<xs:attribute name="StrategyID" type="xs:string" use="required" />
		
		</xs:complexType>
	</xs:element>
	
	
	<xs:element name="Strategy">
		<xs:complexType>
			<xs:sequence>
<!--				<xs:element minOccurs="0" ref="Remark"/> -->
				<xs:element name="PronStrategy" minOccurs="0" maxOccurs="unbounded">
					<xs:complexType>
						<xs:attribute name="refStrategyID" type="xs:string"></xs:attribute>
					</xs:complexType>
				</xs:element>
				
				<xs:element minOccurs="0" ref="Semantics"/>
				<xs:choice>
					
					<xs:element minOccurs="0" ref="Juxtaposition"/>
					<xs:element minOccurs="0" ref="Morphology"/>
				</xs:choice>
				
				<xs:element ref="SyntEnvironment"/>
			
			</xs:sequence>
			<xs:attribute name="SharedWithPronominal" type="xs:string"/>
			<xs:attribute name="Complexity" type="ComplexityAttrType"/>
			<xs:attribute name="Replaceable" type="ReplaceableAttrType" />
			
			<xs:attribute name="StrategyID" type="xs:string"/>
		
		</xs:complexType>
	</xs:element>
	
	<xs:element name="Semantics">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Possessor"/>
				<xs:element ref="Possessed"/>
				<xs:element ref="RelationPRPD"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="Possessor">
		<xs:complexType mixed="true">
			<xs:sequence>
				<xs:element minOccurs="0" maxOccurs="unbounded" ref="Remark"/>
				<xs:element minOccurs="0" maxOccurs="unbounded" ref="Resources"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="Possessed">
		<xs:complexType mixed="true">
			<xs:sequence>
				<xs:element minOccurs="0" maxOccurs="unbounded" ref="Remark"/>
				<xs:element minOccurs="0" maxOccurs="unbounded" ref="Resources"/>
			</xs:sequence>
			<xs:attribute name="ObligatoryPossessed" type="xs:string" use="required"/>
			<xs:attribute name="BodyParts" type="xs:string"/>
			<xs:attribute name="Clothes" type="xs:string"/>
			<xs:attribute name="Kinship" type="xs:string"/>
			<xs:attribute name="Others" type="xs:string"/>
			<xs:attribute name="PlantParts" type="xs:string"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="RelationPRPD">
		<xs:complexType mixed="true">
			<xs:sequence>
				<xs:element minOccurs="0" maxOccurs="unbounded" ref="Remark"/>
				<xs:element minOccurs="0" maxOccurs="unbounded" ref="Resources"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="Juxtaposition">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="0" ref="Remark"/>
				<xs:element ref="CompoundingTest"/>
<!--				<xs:element ref="SyntEnvironment"/> -->
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="CompoundingTest">
		<xs:complexType mixed="true">
			<xs:sequence minOccurs="0" maxOccurs="unbounded">
				<xs:element ref="Text"/>
				<xs:element ref="Gloss"/>
				<xs:element ref="Translation"/>
				<xs:element ref="Resources"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="Morphology">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="0" maxOccurs="unbounded" ref="Pronoun"/>
				<xs:element minOccurs="0" maxOccurs="unbounded" ref="Morpheme"/>
<!--				<xs:element ref="SyntEnvironment"/> -->
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="Morpheme">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="0" maxOccurs="unbounded" ref="Remark"/>
				<xs:element minOccurs="1" maxOccurs="unbounded" ref="morph"/>
				<xs:element ref="Explanation"/>
			
			</xs:sequence>
			<xs:attribute name="Label" type="xs:string"/>
			<xs:attribute name="AttachmentSite" use="required" type="xs:string"/>
			<xs:attribute name="Pronoun" type="xs:string"/>
			<xs:attribute name="SharedWithNominal" type="xs:string"/>
			<xs:attribute name="UsedinPronominal" type="xs:string"/>
			<xs:attribute name="Position" type="xs:string"/>
		<!-- 	<xs:attribute name="pronoun" type="xs:string"/>  -->
		</xs:complexType>
	</xs:element>
	<xs:element name="morph" type="xs:string"/>
	<xs:element name="Remark" type="xs:string"/>
	<xs:element name="Explanation" type="xs:string"/>
	
	<xs:element name="Pronoun">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="0" ref="Remark"/>
				<xs:element minOccurs="0" maxOccurs="unbounded" ref="pron"/>
				<xs:element minOccurs="0" ref="Asymmetry"/>
			</xs:sequence>
			<xs:attribute name="Dedication" use="required"/>
			<xs:attribute name="AttachmentSite" use="required" type="xs:string"/>
			<xs:attribute name="SharedwithNominal" use="required"/>
			<xs:attribute name="Position" />
		
		</xs:complexType>
	</xs:element>
	<xs:element name="pron">
		<xs:complexType mixed="true">
			<xs:attribute name="proximity" type="xs:string"/>
			<xs:attribute name="gender" type="xs:string"/>
			<xs:attribute name="number" use="required" type="xs:string"/>
			<xs:attribute name="person" use="required" type="xs:string"/>
			<xs:attribute name="inclusive" type="xs:string"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="Asymmetry" type="xs:string"/>
	
	<xs:element name="SyntEnvironment">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Adnominal" minOccurs="0" maxOccurs="unbounded" type="ExampleType"/>
				<xs:element name="Predicative" maxOccurs="unbounded" type="ExampleType"/>
				<xs:element name="EllidedPossessed" maxOccurs="unbounded" type="ExampleType"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	
	<xs:element name="Remarks" type="xs:normalizedString"/>
	<!-- <xs:element name="Text" type="xs:string"/> -->
	<xs:element name="Text">
		<xs:complexType mixed="true">
			<xs:choice maxOccurs="unbounded" minOccurs="0">
				<xs:element name="pPron" type="xs:string"></xs:element>
				<xs:element name="pMorp" type="xs:string"></xs:element>
				<xs:element name="pPosed" type="xs:string"></xs:element>
				<xs:element name="pPosor" type="xs:string"></xs:element>

			</xs:choice>
		</xs:complexType>
	
	</xs:element>
	<xs:element name="Gloss" type="xs:string"/>
	<xs:element name="Translation" type="xs:string"/>
	
	<xs:element name="Resources" type="xs:string" />
	
	<xs:complexType name="ExampleType">
		<xs:sequence>
			<xs:element ref="Remarks" minOccurs="0" />
			<xs:element ref="Text" minOccurs="0" />
			<xs:element ref="Gloss" minOccurs="0" />
			<xs:element ref="Translation" minOccurs="0" />
			<xs:element ref="Resources" minOccurs="0" />
		
		</xs:sequence>
		</xs:complexType>
	
	
	<xs:simpleType name="ComplexityAttrType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="simplex" />
			<xs:enumeration value="complex" />
		</xs:restriction>
	</xs:simpleType>
	
	<xs:simpleType name="ReplaceableAttrType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="yes" />
			<xs:enumeration value="?yes" />
			<xs:enumeration value="no" />
			<xs:enumeration value="?no" />
			<xs:enumeration value="??" />
		</xs:restriction>
	</xs:simpleType>
	
	
	<xs:simpleType name="ObligatoryPossessed">
		<xs:restriction base="xs:string">
			<xs:enumeration value="yes" />
			<xs:enumeration value="Partially" />
			<xs:enumeration value="no" />
			<xs:enumeration value="?no" />
			<xs:enumeration value="??" />
		</xs:restriction>
	</xs:simpleType>

</xs:schema>

=== kadim-git/LangPosseisson/_pilotSchema_9.xml
<?xml version="1.0" encoding="UTF-8"?>
<LanguageData xsi:noNamespaceSchemaLocation="_pilotSchema_9.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<Language>
		<GeneralInfo>
			<LangID>Baure</LangID>
			<ISO639-3>brg</ISO639-3>
			<Location>South America</Location>
			<Country>Bolivia</Country>
			<GeneticRelation> Arawakan/Maipurean</GeneticRelation>
			<WordOrder>???</WordOrder>
			<CaseSystem>???</CaseSystem>
			<NominalPhrase>???</NominalPhrase>
			<!-- Comment here to show how Git Hub works -->
			<InterchangeaStrategies></InterchangeaStrategies>
			<RelStrategies></RelStrategies>
		</GeneralInfo>
		<Possession>
			<PronominalPossession>
					<!--  StrategyID="5" is the default to mark elided possessed, this is the strategy used for Spanish borrowings??? -->
				<StrategyPronom Complexity="symplex" StrategyID="1"> 
					 <!-- <Remark>This strategy makes use of bound roots. These roots are also often parts of s. They don't appear on their own, a special prefix -e is needed to make the noun unpossessed. This difference between the two strategies cannot be reflectedd properly in our database
				But it can be seen in one additional pronoun form "unspecified"
 
				</Remark> -->
					<Semantics>
						<Posessor> 
human, plant, animal
							<Resources>Danielsen2007</Resources>
						</Posessor>
						<Possessed ObligatoryPossessed="partially" BodyParts="all" PlantParts="all" Clothes="all" Kinship="all non-Spanish" Others="some">
						non-obligatorily possessed: glasses, etc.	
						<Remark>Kinship terms which are borrowed from Spanish use another strategy to mark possession - with possessive pronoun (nowadays they are in use much more than the original Baure words)
						</Remark>
						body parts: head, brain, eye, tongue, tooth, skin, face, back, hand palm, plant parts: leaf, stem, branch, tree, kinship, clothes (although borrowed from Spanish), 'field', 'feather', 'horn'
						<Resources>Danielsen2007</Resources>
						</Possessed>
						<RelationPRPD>
							inalienable
					       	<Resources>Danielsen2007:118</Resources>
						</RelationPRPD>
					</Semantics>
					<Morphology>
						<Pronoun Dedication="Not dedicated" SharedwithNominal="yes" Placement="Possessed">
							<Remark>The same pronominal clitics mark subject agreement on the verbs (and object agreement) Danielsen2007: 92
					</Remark>
							<pron person="1" number="singular">ni-</pron>
							<pron person="1" number="plural">vi-</pron>
							<pron person="2" number="singular">pi-</pron>
							<pron person="2" number="plural">yi-</pron>
							<pron person="3" number="singular" gender="msc">ro-</pron>
							<pron person="3" number="singular" gender="fem">ri-</pron>
							<pron person="3" number="plural">no-</pron>
							<pron person="unspecified" number="unspecified">e-</pron>
							<Asymmetry></Asymmetry>
						</Pronoun>
					</Morphology>
					<SyntEnvironment>
					<!--	<Adnominal>
							<Text>ntorak to e-ser</Text>
							<Gloss>1sg=find art unspecified-tooth</Gloss>
							<Translation>I found a tooth (I don't know whose)</Translation>
							<Resources></Resources>
						</Adnominal> -->
						<Adnominal>
							<Text><pPron>ni</pPron><pPosed>hačkis</pPosed></Text>
							<Gloss>1sg=glasses</Gloss>
							<Translation>my glasses</Translation>
							<Resources></Resources>
						</Adnominal>
						<Predicative SpecialForm="?">
							<Text></Text>
							<Gloss></Gloss>
							<Translation></Translation>
							<Resources>not_found</Resources>
						</Predicative>
						<EllidedPossessed SpecialForm="?">
							<Text></Text>
							<Gloss></Gloss>
							<Translation></Translation>
							<Resources>not_found</Resources>
						</EllidedPossessed>
					</SyntEnvironment>
				
				</StrategyPronom>
	<!--			<Strategy Complexity="symplex" Replaceable="no" StrategyID="2">
					<Semantics>
						<Posessor> 
								?
							<Resources></Resources>
						</Posessor>
						<Possessed ObligatoryPossessed="no">
						'glasses'
						<Resources>Danielsen2007</Resources>
						</Possessed>
						<RelationPRPD>
							alienable
							<Resources>Danielsen2007:123</Resources>
						</RelationPRPD>
					</Semantics>
					<Morphology>
						<Pronoun Dedication="Not dedicated" SharedwithNominal="yes" Placement="Possessed">
							<Remark>The same pronominal clitics mark subject agreement on the verbs (and object agreement) Danielsen2007: 92
					</Remark>
							<pron person="1" number="singular">ni-</pron>
							<pron person="1" number="plural">vi-</pron>
							<pron person="2" number="singular">pi-</pron>
							<pron person="2" number="plural">yi-</pron>
							<pron person="3" number="singular" gender="msc">ro-</pron>
							<pron person="3" number="singular" gender="fem">ri-</pron>
							<pron person="3" number="plural">no-</pron>
							<Asymmetry></Asymmetry>
						</Pronoun>
					</Morphology>
					<SyntEnvironment>
						<Adnominal>
							<Text>nihačkis</Text>
							<Gloss>1sg=glasses</Gloss>
							<Translation>my glasses</Translation>
							<Resources></Resources>
						</Adnominal>
						<Predicative SpecialForm="?">
							<Text></Text>
							<Gloss></Gloss>
							<Translation></Translation>
							<Resources>not_found</Resources>
						</Predicative>
						<EllidedPossessed SpecialForm="?">
							<Text></Text>
							<Gloss></Gloss>
							<Translation></Translation>
							<Resources>not_found</Resources>
						</EllidedPossessed>
					</SyntEnvironment>
				</Strategy> -->
				<StrategyPronom Complexity="complex" StrategyID="2">
					<Semantics>
						<Posessor> 
								?				
							<Resources></Resources>
						</Posessor>
						<Possessed ObligatoryPossessed="no">
						'firewood', 'jar', 'chief', 'basket', 'blood', 'water', 'fire'
						<Resources>Danielsen2007</Resources>
						</Possessed>
						<RelationPRPD>
							alienable
							<Resources>Danielsen2007:123</Resources>
						</RelationPRPD>
					</Semantics>
					<Morphology>
						<Pronoun Dedication="Not dedicated" SharedwithNominal="yes" Placement="Possessed">
							<Remark>The same pronominal clitics mark subject agreement on the verbs (and object agreement) Danielsen2007: 92
					</Remark>
							<pron person="1" number="singular">ni-</pron>
							<pron person="1" number="plural">vi-</pron>
							<pron person="2" number="singular">pi-</pron>
							<pron person="2" number="plural">yi-</pron>
							<pron person="3" number="singular" gender="msc">ro-</pron>
							<pron person="3" number="singular" gender="fem">ri-</pron>
							<pron person="3" number="plural">no-</pron>
						</Pronoun>
						<Morpheme SharedWithNominal="yes" Placement="Possessed">
							<morph> 
					-no
					</morph>
							<Explanation>This morpheme is a "nominlaizer", it has many usages in the language, see 5.2.4,  9.4, 10.2</Explanation>
						</Morpheme>
					</Morphology>
					<SyntEnvironment>
						<Adnominal>
							<Text><pPron>ni-</pPron><pPosed>hapi</pPosed><pMorp>-n</pMorp></Text>
							<Gloss>1sg=jar=poss</Gloss>
							<Translation>my jar</Translation>
							<Resources>Danielsen2007:12</Resources>
						</Adnominal>
						<Predicative SpecialForm="?">
							<Text></Text>
							<Gloss></Gloss>
							<Translation></Translation>
							<Resources>not_found</Resources>
						</Predicative>
						<EllidedPossessed SpecialForm="?">
							<Text></Text>
							<Gloss></Gloss>
							<Translation></Translation>
							<Resources>not_found</Resources>
						</EllidedPossessed>
					</SyntEnvironment>
				</StrategyPronom>
				<StrategyPronom Complexity="complex" StrategyID="3">
					<Semantics>
						<Posessor> 
								?humans				
							<Resources></Resources>
						</Posessor>
						<Possessed ObligatoryPossessed="no">
						animals
						<Resources>Danielsen2007</Resources>
						</Possessed>
						<RelationPRPD>
							alienable
/inalienable
							<Resources>Danielsen2007:124</Resources>
						</RelationPRPD>
					</Semantics>
					<Morphology>
						<Pronoun Dedication="Not dedicated" SharedwithNominal="yes" Placement="Possessed">
							<Remark>The same pronominal clitics mark subject agreement on the verbs (and object agreement) Danielsen2007: 92
					</Remark>
							<pron person="1" number="singular">ni-</pron>
							<pron person="1" number="plural">vi-</pron>
							<pron person="2" number="singular">pi-</pron>
							<pron person="2" number="plural">yi-</pron>
							<pron person="3" number="singular" gender="msc">ro-</pron>
							<pron person="3" number="singular" gender="fem">ri-</pron>
							<pron person="3" number="plural">no-</pron>
						</Pronoun>
						<Morpheme SharedWithNominal="?yes" Placement="free">
							<morph> 
					-per
					</morph>
							<Explanation>-per 'domestic animal'</Explanation>
						</Morpheme>
					</Morphology>
					<SyntEnvironment>
						<Adnominal>
							<Text><pPron>ni</pPron><pMorp>-per</pMorp> <pPosed>kove'</pPosed></Text>
							<Gloss>1sg=dom.animal dog</Gloss>
							<Translation>my dog</Translation>
							<Resources>Danielsen2007:124</Resources>
						</Adnominal>
						<Predicative SpecialForm="?">
							<Text></Text>
							<Gloss></Gloss>
							<Translation></Translation>
							<Resources>not_found</Resources>
						</Predicative>
						<EllidedPossessed SpecialForm="?">
							<Text></Text>
							<Gloss></Gloss>
							<Translation></Translation>
							<Resources>not_found</Resources>
						</EllidedPossessed>
					</SyntEnvironment>
				</StrategyPronom>
				<StrategyPronom Complexity="symplex" StrategyID="4">
					<Semantics>
						<Posessor> 
								?
							<Resources></Resources>
						</Posessor>
						<Possessed ObligatoryPossessed="no">
